version: '3'

services:
  redis:
    image: redis
    container_name: "personContainer"
    ports:
      - 6379:6379
  writecontainer:
    build: ./writecontainer
    links:
      - redis:personContainer
  readcontainer:
    build: ./readcontainer
    links:
      - redis:personContainer
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "0.0.0.0:8080:8080"

